UPDATE `qa_indicators` SET `qa_criteria` = '<H5><a href=\"https://drive.google.com/file/d/1A8cKOAhV114qrZ2j0_SlH1iwClCOQXRL/view?usp=sharing\" target=\"_blank\">See innovations guidance</a> <br></H5>' WHERE (`id` = '1');
UPDATE `qa_indicators` SET `qa_criteria` = '<H5><a href=\"https://drive.google.com/file/d/1bLzVOrQ0hkqu7EIQr75um1z-VZVHNqV6/view?usp=sharing\" target=\"_blank\">See policies guidance</a> <br></H5>' WHERE (`id` = '2');
UPDATE `qa_indicators` SET `qa_criteria` = '<H5><a href=\"https://drive.google.com/file/d/1-62qwf61xCc-BawTV6HVW410JEE4spg8/view?usp=sharing\" target=\"_blank\">See Peer reviewed paper guidance</a> <br></H5>' WHERE (`id` = '3');
UPDATE `qa_indicators` SET `qa_criteria` = '<H5><a href=\"https://drive.google.com/file/d/1xOZC1MNEpklYre65Ns__TgxAIwz9pjQI/view?usp=sharing\" target=\"_blank\">See OICRs guidance</a> <br></H5>' WHERE (`id` = '4');
UPDATE `qa_indicators` SET `qa_criteria` = '<H5><a href=\"https://drive.google.com/file/d/1L5_xiNP-KXu06LSbTcJHLocqFgi48TsT/view?usp=sharing\" target=\"_blank\">See MELIAs guidance</a> <br></H5>' WHERE (`id` = '5');
UPDATE `qa_indicators` SET `qa_criteria` = '<H5><a href=\"https://drive.google.com/file/d/164SmSOcG8VOixHaiBMupo2hxT9t94Jui/view?usp=sharing\" target=\"_blank\">See Capdev guidance</a> <br></H5>' WHERE (`id` = '6');
UPDATE `qa_indicators` SET `qa_criteria` = '<H5><a href=\"https://drive.google.com/file/d/1wKSekxqsyGNJDLcfhPPdBGtqTtJoLhW-/view?usp=sharing\" target=\"_blank\">See Milestones guidance</a> <br></H5>' WHERE (`id` = '7');
UPDATE `qa_indicators` SET `qa_criteria` = '<H5><a href=\"https://drive.google.com/file/d/1EnMGnzayrLoS1VT9rwIDTHlNue7NiDeN/view?usp=sharing\" target=\"_blank\">See SLOs guidance</a> <br></H5>' WHERE (`id` = '8');


UPDATE `qa_general_configuration` SET `anual_report_guideline` = 'https://drive.google.com/file/d/1H1nHYSM6hzESUzlTaGimhjVuV9GqyI7X/view', `innovations_guideline` = 'https://drive.google.com/file/d/1A8cKOAhV114qrZ2j0_SlH1iwClCOQXRL/view?usp=sharing', `capdev_guideline` = 'https://drive.google.com/file/d/164SmSOcG8VOixHaiBMupo2hxT9t94Jui/view?usp=sharing', `peer_review_paper_guideline` = 'https://drive.google.com/file/d/1-62qwf61xCc-BawTV6HVW410JEE4spg8/view?usp=sharing', `policies_guideline` = 'https://drive.google.com/file/d/1bLzVOrQ0hkqu7EIQr75um1z-VZVHNqV6/view?usp=sharing', `oicr_guideline` = 'https://drive.google.com/file/d/1xOZC1MNEpklYre65Ns__TgxAIwz9pjQI/view?usp=sharing' WHERE (`id` = '1');
UPDATE `qa_general_configuration` SET `anual_report_guideline` = 'https://drive.google.com/file/d/1H1nHYSM6hzESUzlTaGimhjVuV9GqyI7X/view', `innovations_guideline` = 'https://drive.google.com/file/d/1A8cKOAhV114qrZ2j0_SlH1iwClCOQXRL/view?usp=sharing', `capdev_guideline` = 'https://drive.google.com/file/d/164SmSOcG8VOixHaiBMupo2hxT9t94Jui/view?usp=sharing', `peer_review_paper_guideline` = 'https://drive.google.com/file/d/1-62qwf61xCc-BawTV6HVW410JEE4spg8/view?usp=sharing', `policies_guideline` = 'https://drive.google.com/file/d/1bLzVOrQ0hkqu7EIQr75um1z-VZVHNqV6/view?usp=sharing', `oicr_guideline` = 'https://drive.google.com/file/d/1xOZC1MNEpklYre65Ns__TgxAIwz9pjQI/view?usp=sharing' WHERE (`id` = '2');
UPDATE `qa_general_configuration` SET `anual_report_guideline` = 'https://drive.google.com/file/d/1H1nHYSM6hzESUzlTaGimhjVuV9GqyI7X/view', `innovations_guideline` = 'https://drive.google.com/file/d/1A8cKOAhV114qrZ2j0_SlH1iwClCOQXRL/view?usp=sharing', `capdev_guideline` = 'https://drive.google.com/file/d/164SmSOcG8VOixHaiBMupo2hxT9t94Jui/view?usp=sharing', `peer_review_paper_guideline` = 'https://drive.google.com/file/d/1-62qwf61xCc-BawTV6HVW410JEE4spg8/view?usp=sharing', `policies_guideline` = 'https://drive.google.com/file/d/1bLzVOrQ0hkqu7EIQr75um1z-VZVHNqV6/view?usp=sharing', `oicr_guideline` = 'https://drive.google.com/file/d/1xOZC1MNEpklYre65Ns__TgxAIwz9pjQI/view?usp=sharing' WHERE (`id` = '3');
